### ISSUE TITLE
Error while running the pipeline - [Error: Process completed with exit code 1.]

### ISSUE THREAD

**Issue by vishrutkmr7** [sourcery-ai/action#4]
I get the following traceback when running `Sourcery-CLI` on my repository

<img width="874" alt="Screenshot 2022-11-15 at 4 25 37 AM" src="https://user-images.githubusercontent.com/12652202/201908158-b60b0c29-a963-4fac-9efb-62fcb4984240.png">

**Comment by ruancomelli** [comment]
Hey @vishrutkmr7! Thanks for reporting this issue - no one else has reported it yet!

Can you clarify a couple of things, please?

* does this happen in CI (for instance, using the Sourcery GitHub Action), or locally by running `sourcery review <...>`, or in both?
* what Sourcery version are you using? You can check that by running `sourcery --version`.
* do you have a piece of code that I could use to reproduce your issue?

**Comment by vishrutkmr7** [comment]
- This is happening only on the GitHub action and not locally
- `sourcery, version 0.12.9`
- I've been using it on my public repository [My Leetcode Submissions](https://github.com/vishrutkmr7/MyLeetCodeSubmissions)

**Comment by bm424** [comment]
Hi @vishrutkmr7, I've just had a look at this and I've been able to reproduce it -- you can actually get the same result locally by using the `--verbose` flag while running `sourcery review`. 

This is a bug in our core engine, so we'll work towards a fix for the root cause in the next release.

For a quick fix, I'd suggest setting `verbose: false` in the `sourcery.yml` file for your action, like this:

```yaml
name: Check codebase using Sourcery

on:
  workflow_run:
    workflows: [Sync Leetcode]
    types:
      - completed
  push:
    branches: [main]

jobs:
  review-with-sourcery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - uses: sourcery-ai/action@v1
        with:
          token: ${{ secrets.SOURCERY_TOKEN }}
          verbose: false
```

This should bypass the verbose output and allow Sourcery to exit successfully.
